config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get  'login', action: :new
    post 'login', action: :create
    get 'logout', action: :destroy
  end

  resources :books
  resources :users

  root to: 'users#show'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :show, User, id: user.id
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :issued_books, dependent: :destroy
  has_many :user, through: :issued_books

  validates :name, :quantity, presence: true
  validate :copies_issued_cannot_be_greater_than_quantity

  scope :available, -> { where('copies_issued < quantity') }

  def available_copies
    quantity - copies_issued
  end

  private
    def copies_issued_cannot_be_greater_than_quantity
      if copies_issued > quantity
        errors.add(:base, I18n.t(:copies_issued_cannot_be_greater_than_quantity))
      end
    end
end

app/models/concerns/role_finder.rb
module RoleFinder
  extend ActiveSupport::Concern

  included do
    define_role_finders
  end

  module ClassMethods

    def define_role_finders
      class << self
        Role.pluck(:name).each do |name|
          define_method "#{name}" do
            find_by(name: name)
          end
        end
      end
    end

  end
end

app/models/concerns/role_helpers.rb
module RoleHelpers
  extend ActiveSupport::Concern

  included do
    define_role_validators
  end

  module ClassMethods

    def define_role_validators
      Role.pluck(:name).each do |name|
        define_method "#{name}?" do
          role == Role.find_by(name: name)
        end
      end
    end

  end
end

app/models/issued_book.rb
class IssuedBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates :book_id, :user_id, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  include RoleFinder

  validates :name, presence: true
  validates :name, uniqueness: { allow_blank: true, case_sensitive: false }

  has_many :users, dependent: :restrict_with_error
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  include RoleHelpers

  belongs_to :role
  has_many :issued_books, dependent: :destroy
  has_many :books, through: :issued_books

  validates :email, :password, :library_id, presence: true
  validates :email, email: true
  validates :password, length: { in: 8..10 }

  before_validation :assign_library_id, if: :new_record?

  private

    def assign_library_id
      self.library_id = "MYLIB#{ 100 + User.count + rand(100) }"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  authorize_resource
  before_action :authorize
  helper_method :current_user

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: 403 }
      format.html { redirect_to root_url, flash: { error: t(:access_denied) } }
    end
  end

  private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def authorize
      redirect_to login_url, alert: t(:access_denied) unless current_user
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: t(:resource_created, resource: 'Book') }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: t(:resource_updated, resource: 'Book') }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: t(:resource_destroyed, resource: 'Book') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :quantity, :copies_issued)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :reset_session, only: [:create, :destroy]
  before_action :set_user, only: :create

  skip_before_action :authorize
  skip_authorize_resource

  def new; end

  def create
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url, notice: t(:login_successful)
    else
      redirect_to login_url, alert: t(:invalid_credentials)
    end
  end

  def destroy
    redirect_to root_url, notice: t(:logout_successful)
  end

  private

    def set_user
      @user = User.find_by(email: params[:email])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find_by(id: params[:id]) || current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :library_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th >Name</th>
      <th >Quantity</th>
      <th >Copies Issued</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.name,  book_path(book) %></td>
        <td><%= book.quantity %></td>
        <td><%= book.copies_issued %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">
      <span class="col-md-9"><%= @book.name %></span>
      <%= link_to 'Edit', edit_book_path(@book), { class: "btn btn-primary col-md-offset-1" } %>
      <%= link_to 'Back', books_path, { class: "btn btn-primary" } %>
    </h3>
  </div>
  <div class="panel-body">
    <div class="container">
      <ul class="list-group">
        <li class="list-group-item">
          <span class="badge"><%= @book.quantity %></span>
          Total Quantity
        </li>
        <li class="list-group-item">
          <span class="badge"><%= @book.copies_issued %></span>
          Copies Issued
        </li>
        <li class="list-group-item">
          <span class="badge"><%= @book.available_copies %></span>
          Available Copies
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">My Library App</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Books Status", books_url %></li>
            <li><%= link_to "All Users", users_url %></li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
                <li><%= link_to "Sign Out", logout_url %></li>
              <% else %>
                <li><%= link_to "Sign in", login_url %></li>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form-horizontal col-md-8 col-md-offset-2" }, url: users_url do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>
      Enter User Details
    </legend>

    <div class="form-group">
      <%= f.label :name, 'Name:', class: "col-md-2" %>
      <div class="col-md-9">
        <%= f.text_field :name, { class: "form-control", maxlength: '200' }%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, 'Email:', class: "col-md-2" %>
      <div class="col-md-9">
        <%= f.email_field :email, { class: "form-control", maxlength: '200' }%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :library_id, 'Library Id:', class: "col-md-2" %>
      <div class="col-md-9">
        <div class="well well-sm library_id_field">
          <p><%= @user.library_id  %></p>
        </div>
        <p class="text-muted">managed internally</p>
      </div>
    </div>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
    <%= link_to 'Back', users_path, class: 'btn btn-success' %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th >Library Id</th>
      <th >Name</th>
      <th >Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="info">
        <td><%= link_to user.library_id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class='container'>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span class="col-md-9"><%= @user.name %></span>
        <%= link_to 'Edit', edit_user_path(@user), { class: "btn btn-primary col-md-offset-1" } %>
        <%= link_to 'Back', users_path, { class: "btn btn-primary" } %>
      </h3>
    </div>
    <div class="panel-body">
      <div class="container">
        <p class="lead">
          <span class="text-primary">Email</span>
          <span class-text="text-primary"><%= @user.email %></span>
        </p>
        <p class="lead">
          <span class="text-primary">Role</span>
          <span class-text="text-primary"><%= @user.role.name %></span>
        </p>
      </div>
    </div>
  </div>

</div>